---
title: "Complaints 06-09-2021"
author: "Daniel Chen"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(primer.data)
library(plotly)
x <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv")
```

```{r}
view(x)
x %>% 
  select(officer_id, po_race, po_sex) %>% 
  group_by(officer_id) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total)) %>% 
  slice(1:10) %>% 
  mutate(off_id = as.character(officer_id)) %>% 
  ggplot(mapping = aes(x = total, y = off_id)) +
  geom_col() +
  labs(title = "Ten officers and number of complaints",
       subtitle = "List of top ten officers with the most complaints",
                x = "Number of Complaints",
       y = "Officer_Id", 
       caption = "Source: Financial Times")+
  theme_minimal()
```


```{r}
x %>% 
  select(officer_id, po_race, po_sex) %>% 
  group_by(officer_id) %>% 
  summarize(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  arrange(desc(total)) %>% 
  group_by(compl_dec) %>% 
  summarize(dec_total = sum(total)) %>% 
  mutate(compl_per = dec_total/sum(dec_total)) %>% 
  ggplot(mapping = aes(x = compl_dec, y = compl_per, fill = compl_per))+
  geom_col()+
  labs(title = "In Philadelphia, a small group of officers generate a disproportionate \nshare of misconduct complaints", subtitle = "Distribution of civilian misconduct complaints, by decile", x = "Officers are ranked by number of complaints and grouped into deciles", y = "", caption = "Source: Financial Times", fill = "")+
  scale_y_continuous(labels = scales::percent_format())+
  scale_x_continuous(breaks = 1:10)+
  theme_classic()
  

```


